name: Run Netatmo Sync

on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:
    inputs:
      date-begin:
        type: string
        description: Date Begin (YYYY-MM-DDTHH:mm:ss.000Z format, optional)
        required: false
      date-end:
        type: string
        description: Date End (YYYY-MM-DDTHH:mm:ss.000Z format, optional)
        required: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call Sync Endpoint
        id: syncRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ vars.BASE_URL }}/api/sync?date_begin=${{ github.event.inputs.date-begin }}&date_end=${{ github.event.inputs.date-end }}"
          method: "GET"
          bearerToken: ${{ secrets.CRON_SECRET }}
      - name: Show Response
        run: |
          echo ${{ steps.syncRequest.outputs.status }}
          echo ${{ steps.syncRequest.outputs.response }}
