name: Run Netatmo Sync

on:
  # schedule:
  #   - cron: 0 * * * *
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call Sync Endpoint
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://netatmo-sync.vercel.app/api/sync"
          method: "GET"
          bearerToken: ${{ secrets.CRON_SECRET }}
