name: Run Netatmo Sync

on:
  # schedule:
  #   - cron: 0 * * * *
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call Sync Endpoint
        id: syncRequest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ env.BASE_URL }}/api/sync"
          method: "GET"
          bearerToken: ${{ secrets.CRON_SECRET }}
      - name: Show Response
        run: |
          echo ${{ steps.syncRequest.outputs.status }}
          echo ${{ steps.syncRequest.outputs.response }}
